# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f32e91dd7b16b2823165b945117a414d6224045b7f90045999fafbdd0014a1752d9e88cd76f7d44ceddce167f2e05a91ca88ab08ac10934ec78565fad935f7

test:
  secret_key_base: b46ec2b050aa795edcdbfa98045e5ae8fc700b5c6f14748bd0bc457ecddba87d877aded2d9ee29af98fe0686d7d9d903db04a3faf9bb29d7eaa374d98a1e570c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
